### ISSUE TITLE
Manual Control UI Improvements

### ISSUE THREAD

**Issue by quajak** [jschirrmacher/zerberus#9]
- [ ] Use some css (dark theme)
- [ ] Show if motor is blocking
- [ ] Show current speed of robot

**Comment by jschirrmacher** [comment]
Maybe `/remote.html` is a good start.

**Comment by jschirrmacher** [comment]
With the new frontend (#140) this should be considered done.
